### ISSUE TITLE
New-Repository

### ISSUE THREAD

**Issue by Jaykul** [PoshCode/PSGit#1]
Need to create the "initialize" functionality

**Comment by KirkMunro** [comment]
Since it's for initializing the repo, why not just call it Initialize-Repository?  I get that it's creating a new git repository, so maybe New might be a better verb in that case, but Initialize is better from the perspective of knowledge transfer to/from git native commands.

**Comment by jrich523** [comment]
I would say thats just a git wording, its really creating a new repo... its not taking something that exists and setting it up.. if that makes sense... i cant think of a good example off hand... but something like

get-thing | initialize-thing 

seems a more realistic use of initialize-*
