### ISSUE TITLE
How to use? Conflict with other modules?

### ISSUE THREAD

**Issue by arberg** [PoshCode/PSGit#59]
### My version ###
- PsGit: "c:\Program Files\WindowsPowerShell\Modules\PSGit\2.1.0" 
--- but Get-Module PsGit returns nothing
- posh-git version/path: 0.7.3.1  C:\Tools\poshgit\dahlbyk-posh-git-9bda399\src
- PowerShell version: 5.1.17134.407
- git version 2.20.1.windows.1
- OS: Microsoft Windows NT 10.0.17134.0

### My issue ###
I tried using this interesting project. I think I have problems installing it.

I did: `Install-Module PSGit`
I got error: 

> The following commands are already available on this system:'Write-Host'. This
> module 'Pansies' may override the existing commands

I did the dare-devil thing and tried: `Install-Module PSGit -AllowClobber`
This time no error.
However: `Get-Module psgit` returns nothing

When I open a new powershell prompt an run `import-module psgit' I get some changes. The prompt in a git working repo, now contains 

> [master ≡][ master []:>

indicating posh-git and psgit both working.

I found if posh-git and psgit both use the name Get-GitStatus. I guess that's natural. 

Maybe I don't have a question anymore, but its worth noting the install problem, and the lack of documentation. But I would say PsGit looks interesting :)

**Comment by Jaykul** [comment]
After `Install-Module PSGit -AllowClobber` the module is installed, and as you discovered, if you `Import-Module PSGit` it imports

The `Get-Module` command only shows modules which are already imported, unless you use `-ListAvailable`  (the **opposite** of the `Get-Command` command, which has a `-ListImported` switch)

And yes, I did use the same command name, because I was trying to be a drop-in for users who use posh-git just for their prompt ...

**Comment by arberg** [comment]
Thanks for the info. I guess its a good idea to use the same command name Get-GitStatus. Its output-content is not quite the same, though similar. You've added some lacking features like isHead and Tip. There following are not in ps-git, you are probably aware of this, but just in case its new in posh-git here it is:

StashCount
Upstream
HasWorking (changes not added to index)
HasIndex (index changes)
HasUntracked (has untracked files)
Working (changes files)
Index (changes files)
UpstreamGone
GitDir

I find the first five listed quite useful, and I would miss them as I print status to user in a nice overview of submodules.
